name: "sentiment-analysis"
on:
  pull_request:
  push:
    branches:
      - main
      - 'v*'

jobs:
  # unit tests
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Run sentiment analysis on HTML files"
      uses: bogdaaamn/copy-sentiment-analysis@v0.5.1
      with: 
        gcp_key: ${{ secrets.GCP_KEY }} 
    - run: |
        "ls"

